

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ToyProject?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root1234!!

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kakao-api:
    key: ${API_KEY}

jwt:
  secret: kCXoHrvI0tyx66krErbdTIjUrylFcJQLq4IFSy0NYdNVWWSggYFRWOvuSNsswJtp

server:
  address: localhost
  #  error:
  #    include-stacktrace: never
  port: 8080
